# Generated by Django 2.2.7 on 2019-11-24 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='category',
            new_name='status',
        ),
    ]
